name: CI
# on: [release]
on:
  push:
  release:
    types: [published]

jobs:
  create-test-files:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: zip it
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'zipped-release.zip'
          directory: '.'
          path: '.'
          exclusions: '*.git* /*node_modules/* **/*.zip'
      # - name: create some rel-test content
      #   run: |
      #     mkdir rel-test
      #     cd rel-test
      #     touch rel-test.txt
      - name: Display files
        run: ls -R
      - name: upload test
        uses: actions/upload-artifact@master
        with:
          name: zipped-release.zip
          path: zipped-release.zip
  upload-to-release:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: [create-test-files]
    if: github.event_name == 'release'
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: download atrifacts zipped-release.zip
        uses: actions/download-artifact@master
        with:
          name: zipped-release.zip
      - name: Upload to release
        if: github.event_name == 'release'
        uses: JasonEtco/upload-to-release@v0.1.1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          args: zipped-release.zip application/zip
