name: Labeler
on: [push]

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
      - name: Install zip
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r public.zip . -i public
      # - name: Zip output
      #   run: zip -qq -r test.zip . -i package.json
      # run: zip -qq -r test.zip package.json
      # working-directory: test/zip/
